---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    # Look for a `Dockerfile` in the `root` directory
    directory: /
    schedule:
      interval: daily
      #interval: weekly

...
